# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LibraryShowcase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LibraryShowcase
  pod 'Alamofire', '~> 4.4'
  pod "AsyncDisplayKit"
pod 'BonMot'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

pod 'Charts/Realm'
  pod 'CryptoSwift'
pod 'DZNEmptyDataSet'
pod 'DeviceKit', '~> 1.0'
pod 'FSCalendar'
pod 'FileKit', '~> 4.0.0'
    pod 'GDPerformanceView-Swift', '~> 1.1.2'
pod 'IGListKit', '~> 2.0.0'
pod 'ImageViewer'
  pod 'Kingfisher', '~> 3.0'
pod 'MGSwipeTableCell'

pod 'Hero'



end
